- name: "add node.js"
  become: true
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    source ~/.bashrc
    nvm install v13.8.0
- name: "install pm2"
  npm:
    name: pm2
    global: yes
